# Generated by Django 4.2.3 on 2023-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
