# Generated by Django 4.2.3 on 2023-07-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
