# Generated by Django 4.2.3 on 2023-07-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='payment_method',
            field=models.CharField(choices=[('PP', 'PayPal'), ('ZL', 'Zelle'), ('BT', 'Bank Transfer')], default='PP', max_length=2),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
