# Generated by Django 4.2.3 on 2023-08-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippingadress_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='transfer_reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
