# Generated by Django 4.2.3 on 2023-08-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_phone_number'),
        ('store', '0008_shippingadress_transfer_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('PP', 'PayPal'), ('ZL', 'Zelle'), ('BT', 'Bank Transfer')], default='PP', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('transfer_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAdress',
        ),
    ]
